from pylab import *

#Evans60
#Density
clf()
B = loadtxt("data/evans60/ne60.dat")
grid(True)
xlim(0.0,1.)
plot(B[:,0],B[:,1],'k',label=r'$n_{e}$')
#plot(B[:,0],B[:,2],'k--',label='Im')
xlabel(r'$a_{N}$')
ylabel(r'$n_{e}$,[$10^{19}m^{-3}$]')
legend()
savefig("graphics/ne60.png")

#Temperature
clf()
B = loadtxt("data/evans60/T60.dat")
grid(True)
xlim(0.0,1.)
plot(B[:,0],B[:,1],'k',label=r'$T_{e}$')
plot(B[:,0],B[:,2],'k--',label=r'$T_{i}$')
xlabel(r'$a_{N}$')
ylabel('T, [eV]')
legend()
savefig("graphics/T60.png")

#Pressure
clf()
B = loadtxt("data/evans60/P60.dat")
grid(True)
xlim(0.0,1.)
plot(B[:,0],B[:,1],'k',label=r'$p_{e}$')
plot(B[:,0],B[:,2],'k--',label=r'$p_{i}$')
plot(B[:,0],B[:,3],'k--',label=r'$p_{total}$')
xlabel(r'$a_{N}$')
ylabel('p, [Pa]')
legend()
savefig("graphics/P60.png")

#Pressure gradient
clf()
B = loadtxt("data/evans60/dP60.dat")
grid(True)
xlim(0.85,1.)
ylim(-200.,0.)
plot(B[:,0],1.e-3*B[:,1],'k',label=r'$\frac{dp_{e}}{da_{N}}$')
plot(B[:,0],1.e-3*B[:,2],'k--',label=r'$\frac{dp_{i}}{da_{N}}$')
plot(B[:,0],1.e-3*B[:,3],'k:',label=r'$\frac{dp_{total}}{da_{N}}$')
xlabel(r'$a_{N}$')
ylabel('Pressure gradients, [kPa]')
legend(loc='lower left')
savefig("graphics/dP60.png")

#Electric field
clf()
B = loadtxt("data/evans60/E60.dat")
grid(True)
xlim(0.85,1.)
#ylim(-200.,0.)
plot(B[:,0],B[:,1],'k',label=r'$E_{0r}$')
xlabel(r'$a_{N}$')
ylabel('Electric field, [V]')
legend(loc='lower left')
savefig("graphics/E60.png")

#K60
clf()
B = loadtxt("data/evans60/K60.dat")
grid(True)
xlim(0.85,1.)
ylim(-6.e-5,0.)
plot(B[:,0],B[:,1],'k',label=r'$K_{m}$')
xlabel(r'$a_{N}$')
ylabel(r'$K_{m}$, $60^o$')
legend(loc='lower left')
title(r'$K_{m}$ for $60^o$')
savefig("graphics/K60.png")

#Pressure perturbation
clf()
B = loadtxt("data/evans60/ppert.dat")
grid(True)
xlim(0.93,0.97)
#ylim(-200.,0.)
plot(B[:,0],B[:,1],'k',label=r'$ReP$')
plot(B[:,0],B[:,2],'k--',label=r'$ImP$')
#plot(B[:,0],B[:,3],'k:',label=r'$\frac{dp_{total}}{da_{N}}$')
xlabel(r'$a_{N}$')
ylabel('Pressure perturbation, [a.u.]')
legend(loc='lower left')
title(r'Pressure perturbation for $60^o$')
savefig("graphics/perturbation_60.png")

#Q
clf()
B = loadtxt("data/evans60/Q.dat")
grid(True)
xlim(0.93,0.97)
#ylim(-200.,0.)
plot(B[:,0],B[:,1],'k',label=r'$ReQ_{m}$')
plot(B[:,0],B[:,2],'k--',label=r'$ImQ_{m}$')
#plot(B[:,0],B[:,3],'k:',label=r'$\frac{dp_{total}}{da_{N}}$')
xlabel(r'$a_{N}$')
ylabel(r'$Q_{m}$')
legend(loc='lower left')
title(r'$Q_{m}$ for $60^o$')
savefig("graphics/Q60.png")