from pylab import *

#Evans60
#Density
clf()
B = loadtxt("data/evans60/ne60.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.0,1.)
plot(B[:,0],B[:,1],'k',label=r'$n_{e}$',lw=2.5)
#plot(B[:,0],B[:,2],'k--',label='Im')
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$n_{e}$,[$10^{19}m^{-3}$]',fontsize=20)
legend()
savefig("graphics/evans60/ne60.eps")

#Temperature
clf()
B = loadtxt("data/evans60/T60.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.0,1.)
plot(B[:,0],B[:,1],'k',label=r'$T_{e}$',lw=2.5)
plot(B[:,0],B[:,2],'k--',label=r'$T_{i}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel('T, [eV]',fontsize=20)
legend()
savefig("graphics/evans60/T60.eps")

#Pressure
clf()
B = loadtxt("data/evans60/P60.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.0,1.)
plot(B[:,0],1.e-3*B[:,1],'k',label=r'$p_{e}$',lw=2.5)
plot(B[:,0],1.e-3*B[:,2],'k--',label=r'$p_{i}$',lw=2.5)
plot(B[:,0],1.e-3*B[:,3],'k:',label=r'$p_{total}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel('Pressure, kPa',fontsize=20)
legend()
savefig("graphics/evans60/P60.eps")

#Pressure gradient
clf()
B = loadtxt("data/evans60/dP60.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.85,1.)
ylim(-200.,0.)
plot(B[:,0],1.e-3*B[:,1],'k',label=r'$\frac{dp_{e}}{da_{N}}$',lw=2.5)
plot(B[:,0],1.e-3*B[:,2],'k--',label=r'$\frac{dp_{i}}{da_{N}}$',lw=2.5)
plot(B[:,0],1.e-3*B[:,3],'k:',label=r'$\frac{dp_{total}}{da_{N}}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel('Pressure gradients, [kPa]',fontsize=20)
legend(loc='lower left')
savefig("graphics/evans60/dP60.eps")

#Electric field
clf()
B = loadtxt("data/evans60/E60.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.85,1.05)
ylim(-30.,20.)
plot(B[:,0],1.e-3*B[:,1],'k',label=r'$E_{0r}$',lw=2.5)
plot([0,1.05],[0,0],'k')
xlabel(r'$a_{N}$',fontsize=20)
ylabel('Electric field, [kV]',fontsize=20)
legend(loc='lower left')
savefig("graphics/evans60/E60.eps")

#K60
clf()
B = loadtxt("data/evans60/K60.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.85,1.05)
ylim(-6.,0.)
plot(B[:,0],1.e+5*B[:,1],'k',label=r'$K_{m}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$10^5 K_{m}$, $60^o$',fontsize=20)
legend(loc='lower left')
title(r'$K_{m}$ for $60^o$')
savefig("graphics/evans60/K60.eps")

#A60
clf()
B = loadtxt("data/evans60/A.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.85,1.05)
#ylim(-6.e-5,0.)
plot(B[:,0],B[:,1],'k',label=r'$A(a_N)$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$A(a_N)$',fontsize=20)
legend(loc='lower left')
title(r'$A(a_N)$')
savefig("graphics/evans60/A60.eps")

#Pressure perturbation
clf()
B = loadtxt("data/evans60/ppert.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.93,0.97)
#ylim(-200.,0.)
plot(B[:,0],B[:,1],'k',label=r'Re$P$',lw=2.5)
plot(B[:,0],B[:,2],'k--',label=r'Im$P$',lw=2.5)
#plot(B[:,0],B[:,3],'k:',label=r'$\frac{dp_{total}}{da_{N}}$')
xlabel(r'$a_{N}$',fontsize=20)
ylabel('Pressure perturbation, [a.u.]',fontsize=20)
legend(loc='lower left')
title(r'Pressure perturbation for $60^o$')
savefig("graphics/evans60/perturbation_60.eps")

#Q
clf()
B = loadtxt("data/evans60/Q.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.93,0.97)
#ylim(-200.,0.)
plot(B[:,0],B[:,1],'k',label=r'Re$Q_{m}$',lw=2.5)
plot(B[:,0],B[:,2],'k--',label=r'Im$Q_{m}$',lw=2.5)
#plot(B[:,0],B[:,3],'k:',label=r'$\frac{dp_{total}}{da_{N}}$')
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$Q_{m}$',fontsize=20)
legend(loc='lower left')
title(r'$Q_{m}$ for $60^o$')
savefig("graphics/evans60/Q60.eps")

#Q1
clf()
B = loadtxt("data/evans60/Q1.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.93,0.97)
plot(B[:,0],B[:,1],'k',label=r'Re$Q_{1m}$',lw=2.5)
plot(B[:,0],B[:,2],'k--',label=r'Im$Q_{1m}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$Q_{m}$',fontsize=20)
legend(loc='lower left')
savefig("graphics/evans60/Q1_60.eps")