from pylab import *

#Pressure perturbation
clf()
B = loadtxt("data/znam_.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.93,0.97)
plot(B[:,0],B[:,1],'k',label=r'Re$P_m$',lw=2.5)
plot(B[:,0],B[:,2],'k--',label=r'Im$P_m$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel('Pressure perturbation, a.u.',fontsize=20)
legend(loc='lower left')
savefig("graphics/perturbation.eps")

#Q
clf()
B = loadtxt("data/Q.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.93,0.97)
plot(B[:,0],B[:,1],'k',label=r'Re$Q_{m}$',lw=2.5)
plot(B[:,0],B[:,2],'k--',label=r'Im$Q_{m}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$Q_{m}$',fontsize=20)
legend(loc='lower left')
savefig("graphics/Q.eps")

#Q1
clf()
B = loadtxt("data/Q1.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.93,0.97)
plot(B[:,0],B[:,1],'k',label=r'Re$Q_{1m}$',lw=2.5)
plot(B[:,0],B[:,2],'k--',label=r'Im$Q_{1m}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$Q_{m}$',fontsize=20)
legend(loc='lower left')
savefig("graphics/Q1.eps")

#Density
clf()
B = loadtxt("data/ne.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.0,1.05)
plot(B[:,0],B[:,1],'k',label=r'$n_{e}$',lw=2.5)
#plot(B[:,0],B[:,2],'k--',label='Im')
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$n_{e}$,[$10^{19}m^{-3}$]',fontsize=20)
legend()
savefig("graphics/ne.eps")

#Temperature
clf()
B = loadtxt("data/T.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.0,1.05)
plot(B[:,0],B[:,1],'k',label=r'$T_{e}$',lw=2.5)
plot(B[:,0],B[:,2],'k--',label=r'$T_{i}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel('T, [eV]',fontsize=20)
legend()
savefig("graphics/T.eps")

#Pressure
clf()
B = loadtxt("data/P.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.0,1.05)
plot(B[:,0],1.e-3*B[:,1],'k',label=r'$p_{e}$',lw=2.5)
plot(B[:,0],1.e-3*B[:,2],'k--',label=r'$p_{i}$',lw=2.5)
plot(B[:,0],1.e-3*B[:,3],'k--',label=r'$p_{total}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel('p, [kPa]',fontsize=20)
legend(loc='lower left')
savefig("graphics/P.eps")

#Pressure gradient
clf()
B = loadtxt("data/DP.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.85,1.05)
ylim(-200.,0.)
plot(B[:,0],1.e-3*B[:,1],'k',label=r'$\frac{dp_{e}}{da_{N}}$',lw=2.5)
plot(B[:,0],1.e-3*B[:,2],'k--',label=r'$\frac{dp_{i}}{da_{N}}$',lw=2.5)
plot(B[:,0],1.e-3*B[:,3],'k:',label=r'$\frac{dp_{total}}{da_{N}}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'Pressure gradients, $kPa$',fontsize=20)
legend(loc='lower left')
savefig("graphics/DP.eps")

#Electric field
clf()
B = loadtxt("data/E.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.85,1.05)
#ylim(-200.,0.)
plot(B[:,0],1.e-3*B[:,1],'k',label=r'$E_{0r}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel('Electric field, [kV]',fontsize=20)
legend(loc='lower left')
savefig("graphics/E.eps")

#Km
clf()
B = loadtxt("data/Km_A_.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.85,1.)
ylim(-2,2.)
plot(B[:,0],1.e+5*B[:,1],'k',label=r'$K_{m}$',lw=2.5)
plot([0,1],[0,0],'k-')
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$10^5 K_{m}$',fontsize=20)
legend(loc='lower left')
title(r'$K_{m}$')
savefig("graphics/Km.eps")

#A
clf()
B = loadtxt("data/Km_A_.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.85,1.)
#ylim(-6.e-5,0.)
plot(B[:,0],B[:,2],'k',label=r'$A(a_N)$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$A(a_N)$',fontsize=20)
legend(loc='lower left')
title(r'$A(a_N)$')
savefig("graphics/A.eps")

#Bootstrap current
clf()
B = loadtxt("data/Bootstrap.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.9,1.)
plot(B[:,0],B[:,1],'k',label='Re',lw=2.5)
plot(B[:,0],B[:,2],'k--',label='Im',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel('Calculate: (R/a)**0.5 ...... ',fontsize=20)
legend()
savefig("graphics/Bootstrap.eps")

#Flux
clf()
B = loadtxt("data/Flux.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.0,1.0)
#ylim(0.,1.5)
plot(B[:,0],B[:,1],'k',label=r'$\Psi_{m}$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$\Psi_{m}$',fontsize=20)
legend(loc='upper left')
title(r'$\Psi_{m}$')
savefig("graphics/Flux.eps")

#sigma
clf()
B = loadtxt("data/sigma.dat")
rc('xtick',labelsize=17)    
rc('ytick',labelsize=17) 
grid(True)
xlim(0.0,1.05)
#ylim(0.,1.5)
plot(B[:,0],B[:,1],'k',label=r'$\sigma(a_N)$',lw=2.5)
xlabel(r'$a_{N}$',fontsize=20)
ylabel(r'$\sigma(a_N), sec^{-1}$',fontsize=20)
legend(loc='lower left')
title(r'$\sigma(a_N),sec^{-1}$')
savefig("graphics/sigma.eps")
